### ISSUE TITLE
Example #2 does not work

### ISSUE THREAD

**Issue by Zert** [ozataman/csv-conduit#13]
Code in Example #2 terminated with:

conduit-test: Prelude.undefined

only produced 0-bytes output file.

Why myProcessor is undefined?

**Comment by stormont** [comment]
I've just submitted a pull request to fix this in the master branch, but in the meantime, a simple way to replace it is with:

myProcessor :: Monad m => Conduit (Row Text) m (Row Text)
myProcessor = awaitForever $ yield

**Comment by dmvianna** [comment]
This looks stale, please open again if it is still an issue.
