### ISSUE TITLE
new to haskell, thanks in advance

### ISSUE THREAD

**Issue by waynenilsen** [ozataman/csv-conduit#14]
I am new to Haskell and work with CSV data a ton. The task is to write a database loader that safely checks types extracts specific columns from CSV files etc. We have a relatively specific use case and I think haskell is very well suited to solving this problem but I am new to it and it seems that there is quite a steep learning curve. 

Can you help me convert example one or two from the homepage into a runnable haskell program? Also, how would I modify example two to simply extract a column from a CSV file during the mapping?

**Comment by ozataman** [comment]
Hey there. Always happy to see new interest in Haskell. Unfortunately, I don't think this is the right medium to get help. I would recommend Haskell's reddit, freenode IRC channel or StackOverflow to get that sort of help.

Good luck!
