### ISSUE TITLE
Wrong parsing of rows

### ISSUE THREAD

**Issue by varosi** [ozataman/csv-conduit#27]
I have this file:

> hello,","," ",world,"!"
> hello,","," ",world,"!"
> hello,","," ",world,"!"

Parsing it with this program:
```
    s <- BS.readFile input
    let Right csv = decodeCSV (CSVSettings ',' (Just '"')) s :: Either SomeException (Vector (Row BS.ByteString))
    print . Data.Vector.length $ csv
```

Result is "1". Why?

**Comment by MichaelXavier** [comment]
Probably duplicate of #24 ?

**Comment by dmvianna** [comment]
This issue looks stale, probably solved. If still an issue, feel free to reopen.

**Comment by varosi** [comment]
It has to be tested to see if the issue still persists.

**Comment by dmvianna** [comment]
If you're willing to do it, I'm happy to help.
