### ISSUE TITLE
Cannot build csv-conduit because `runExceptionT` is deprecated from resourcet-1.2.0

### ISSUE THREAD

**Issue by QuietJoon** [ozataman/csv-conduit#32]
I can't build csv-conduit because `runExceptionT` is deprecated since `resourcet-1.2.0`.

    [7 of 7] Compiling Data.CSV.Conduit ( src\Data\CSV\Conduit.hs, dist\build\Data\CSV\Conduit.o )

    src\Data\CSV\Conduit.hs:40:54: error:
        Module
        Control.Monad.Trans.Resource
        does not export
        runExceptionT

    40 |                                                      runExceptionT,

I tried to fix it by myself, but I couldn't because I have no knowledge about how to handle `conduit` and others...

**Comment by MichaelXavier** [comment]
This is merged into master and will go out in the next release.

**Comment by MichaelXavier** [comment]
Released at 0.6.8
