### ISSUE TITLE
Add to Stackage?

### ISSUE THREAD

**Issue by ocramz** [ozataman/csv-conduit#41]
Hi, it would be nice to have this on Stackage. I can help with maintenance if needed as I'm a frequent user. Let me know! Thanks

**Comment by skogsbaer** [comment]
Indeed, it would be nice to have it on stackage. Also, a new release on hackage would be good!

**Comment by dmvianna** [comment]
Yes. My hands are tied, I haven't been given the Hackage permissions. I only have maintainer power in GitHub.

**Comment by MichaelXavier** [comment]
@dmvianna I think I may be able to add you as a hackage maintainer. What's your username?

**Comment by dmvianna** [comment]
https://hackage.haskell.org/user/dmvianna

Cheers!

**Comment by skogsbaer** [comment]
Great! @dmvianna would you also like to add csv-conduit to stackage? Once #54 has been merged and the newest version is on hackage, it's straightforward to get it into stackage: https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by MichaelXavier** [comment]
@dmvianna Added you to the maintainer list on Hackage. Thank you for stepping up! :heart:

**Comment by dmvianna** [comment]
Uploaded `1.0.0.1` to Hackage, opened [PR](https://github.com/commercialhaskell/stackage/pull/7528) at Stackage.
